"""a concept knows which scene to draw

Revision ID: 01e475ad95f6
Revises: 83022f47fa0a
Create Date: 2026-09-24 19:55:50.055410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = '01e475ad95f6'
down_revision: Union[str, Sequence[str], None] = '83022f47fa0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motif', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate proposes `drop_constraint(None, type_='foreignkey')` on
    # `mistakes` every single time. It is always wrong — the constraint was
    # created inline and has no name to drop — and it always has to come out.
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_column('motif')

    # ### end Alembic commands ###
