"""concepts carry their order and its label

Revision ID: 1d0dc1d36bc8
Revises: d2f5b81c6a47
Create Date: 2026-09-20 16:42:34.897334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = '1d0dc1d36bc8'
down_revision: Union[str, Sequence[str], None] = 'd2f5b81c6a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('when_label', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_column('when_label')
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
