"""a concept remembers where it was dragged

Revision ID: 554a51f67702
Revises: e302c66f1257
Create Date: 2026-09-21 22:12:38.846138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = '554a51f67702'
down_revision: Union[str, Sequence[str], None] = 'e302c66f1257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('map_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate proposes dropping an unnamed foreign key on `mistakes` here.
    # It is wrong twice over: this revision never added one, and SQLite cannot
    # drop an anonymous constraint by name - it raises "Constraint must have a
    # name". Alembic re-detects `mistakes.material_id`'s key on every run
    # because it was created without one; the line is noise and is removed.
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_column('map_y')
        batch_op.drop_column('map_x')

    # ### end Alembic commands ###
