"""the review machinery goes

Revision ID: 5e34f50bf444
Revises: 1d0dc1d36bc8
Create Date: 2026-09-20 23:14:59.812934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = '5e34f50bf444'
down_revision: Union[str, Sequence[str], None] = '1d0dc1d36bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_events_due_at'))
        batch_op.drop_index(batch_op.f('ix_review_events_mistake_id'))
        batch_op.drop_index(batch_op.f('ix_review_events_open'))

    op.drop_table('review_events')
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistakes_analysis_status'))
        batch_op.drop_index(batch_op.f('ix_mistakes_error_type'))
        batch_op.drop_index(batch_op.f('ix_mistakes_urgency'))
        batch_op.drop_column('why_wrong')
        batch_op.drop_column('takeaway')
        batch_op.drop_column('urgency_is_yours')
        batch_op.drop_column('analysis_status')
        batch_op.drop_column('urgency')
        batch_op.drop_column('trap')
        batch_op.drop_column('error_type')
        batch_op.drop_column('your_answer')
        batch_op.drop_column('analysis_edited_at')
        batch_op.drop_column('correct_reasoning')
        batch_op.drop_column('analysis_error')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('analyzed_by')
        batch_op.drop_column('analyzed_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyzed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('analyzed_by', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=16), nullable=True))
        batch_op.add_column(sa.Column('analysis_error', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('correct_reasoning', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('analysis_edited_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('your_answer', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('error_type', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('trap', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('analysis_status', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('urgency_is_yours', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('takeaway', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('why_wrong', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mistakes_urgency'), ['urgency'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistakes_analysis_status'), ['analysis_status'], unique=False)

    op.create_table('review_events',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('mistake_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('cycle', sa.INTEGER(), nullable=False),
    sa.Column('step_index', sa.INTEGER(), nullable=False),
    sa.Column('interval_label', sa.VARCHAR(length=8), nullable=False),
    sa.Column('due_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=16), nullable=True),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_events_open'), ['completed_at', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_mistake_id'), ['mistake_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_due_at'), ['due_at'], unique=False)

    # ### end Alembic commands ###
