"""notes written up from a material

Revision ID: 83022f47fa0a
Revises: 554a51f67702
Create Date: 2026-09-21 22:31:49.444500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = '83022f47fa0a'
down_revision: Union[str, Sequence[str], None] = '554a51f67702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('notes_written_at', app.models.UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The unnamed-foreign-key line autogenerate writes here is noise - see
    # CLAUDE.md. This revision did not add it, and SQLite cannot drop it.
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('notes_written_at')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
