"""a folder is a working set: its own brief and its synthesis

Revision ID: c20ca9a2f9a0
Revises: 20bb49a8ca10
Create Date: 2026-09-25 22:13:45.501945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = 'c20ca9a2f9a0'
down_revision: Union[str, Sequence[str], None] = '20bb49a8ca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('digest', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('digest_written_at', app.models.UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate proposes `drop_constraint(None, type_='foreignkey')` on
    # `mistakes` every single time. It is always wrong and always comes out.
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('digest_written_at')
        batch_op.drop_column('digest')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
