"""materials: the record of what you put in

Revision ID: e302c66f1257
Revises: 5e34f50bf444
Create Date: 2026-09-20 23:33:19.584157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = 'e302c66f1257'
down_revision: Union[str, Sequence[str], None] = '5e34f50bf444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=True),
    sa.Column('folder_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=400), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_user_id'), ['user_id'], unique=False)

    op.create_table('material_concepts',
    sa.Column('material_id', sa.String(length=32), nullable=False),
    sa.Column('concept_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id', 'concept_id')
    )
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_mistakes_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No `drop_constraint` for the foreign key: it was created unnamed, and SQLite
    # cannot drop an anonymous constraint by name. Batch mode rebuilds the table
    # from the remaining columns anyway, so dropping the column takes the key with
    # it - and asking for the constraint first fails with "must have a name".
    with op.batch_alter_table('mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistakes_material_id'))
        batch_op.drop_column('material_id')

    op.drop_table('material_concepts')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_user_id'))
        batch_op.drop_index(batch_op.f('ix_materials_subject'))
        batch_op.drop_index(batch_op.f('ix_materials_folder_id'))

    op.drop_table('materials')
    # ### end Alembic commands ###
